//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Adt
{
    [Serializable]
    public class ChatMsg : Message
    {
        public const string k_RosMessageName = "adt_msgs/Chat";
        public override string RosMessageName => k_RosMessageName;

        public StringMsg message;

        public ChatMsg()
        {
            this.message = new StringMsg();
        }

        public ChatMsg(StringMsg message)
        {
            this.message = message;
        }

        public static ChatMsg Deserialize(MessageDeserializer deserializer) => new ChatMsg(deserializer);

        private ChatMsg(MessageDeserializer deserializer)
        {
            this.message = StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ChatMsg: " +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
