<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="service_roboter">
    <xacro:property name="axis_length_x" value="4.0" />
    <xacro:property name="axis_length_y" value="1.5" />
    <xacro:property name="axis_length_z" value="0.6" />
    
    <xacro:property name="table_x" value="${axis_length_x}" />
    <xacro:property name="table_y" value="${axis_length_y}" />
    <xacro:property name="table_z" value="0.025" />
    
    <xacro:property name="head_x" value="0.1" />
    <xacro:property name="head_y" value="0.2" />
    <xacro:property name="head_z" value="0.015" />

    <xacro:property name="sled_x" value="0.1" />
    <xacro:property name="sled_y" value="0.015" />
    <xacro:property name="sled_z" value="0.2" />


    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0 0.9 0.9 1.0"/>
	     	</material>
        </visual>
    </link>


    <link name="table_link">
        <visual>
            <origin xyz="${table_x/2} ${table_y/2} -${table_z/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${table_x} ${table_y} ${table_z}"/>
            </geometry>
        </visual>
    </link>
    <joint name="table_joint" type="fixed">
        <parent link="base_link"/>
        <child link="table_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <link name="head_link">
        <visual>
            <origin xyz="${head_x/2} ${head_y/2} ${head_z/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${head_x} ${head_y} ${head_z}"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0.9 0.0 0.0 1.0"/>
	     	</material>
        </visual>
    </link>
    <joint name="head_joint" type="fixed">
        <parent link="head_z_link"/>
        <child link="head_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="head_x_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0 0.9 0.9 1.0"/>
	     	</material>
        </visual>
    </link>
    <joint name="head_x_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="head_x_link"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="0.0" upper="${axis_length_x - head_x}" velocity="0.5" effort="1000.0"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="head_y_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0 0.9 0.9 1.0"/>
	     	</material>
        </visual>
    </link>
    <joint name="head_y_joint" type="prismatic">
        <parent link="head_x_link"/>
        <child link="head_y_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="${axis_length_y - head_y}" velocity="0.5" effort="1000.0"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="head_z_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0 0.9 0.9 1.0"/>
	     	</material>
        </visual>
    </link>
    <joint name="head_z_joint" type="prismatic">
        <parent link="head_y_link"/>
        <child link="head_z_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="0.0" upper="${axis_length_z}" velocity="0.5" effort="1000.0"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="sled_right_link">
        <visual>
            <origin xyz="${sled_x/2} -${sled_y/2} ${-sled_z/2 + axis_length_z / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${sled_x} ${sled_y} ${sled_z + axis_length_z / 2}"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0.9 0.9 0.0 1.0"/>
	     	</material>
        </visual>
    </link>
    <joint name="sled_right_joint" type="fixed">
        <parent link="head_x_link"/>
        <child link="sled_right_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="sled_left_link">
        <visual>
            <origin xyz="${sled_x/2} ${sled_y/2 + axis_length_y} ${-sled_z/2 + axis_length_z / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${sled_x} ${sled_y} ${sled_z + axis_length_z / 2}"/>
            </geometry>
			<material name="Cyan">
	       		<color rgba="0.9 0.9 0.0 1.0"/>
	     	</material>
        </visual>
    </link>
    <joint name="sled_left_joint" type="fixed">
        <parent link="head_x_link"/>
        <child link="sled_left_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    

</robot>