<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="service_roboter">
    <xacro:property name="barrel_radius" value="0.290" />
    <xacro:property name="barrel_hight"  value="0.900" />

    <xacro:property name="wheel_radius"  value="0.150" />
    <xacro:property name="wheel_width"   value="0.050" />
    <xacro:property name="wheel_peakout" value="0.050" />

    <link name="base_link"/>

    <link name="barrel_link">
        <visual>
            <origin xyz="0.0 0.0 ${barrel_hight / 2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${barrel_radius}" length="${barrel_hight}"/>
            </geometry>
        </visual>
    </link>
    <joint name="barrel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="barrel_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="wheel_left_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </visual>
    </link>
    <joint name="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_link"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0.0 ${barrel_radius/2.0} ${wheel_radius-wheel_peakout}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    
    <link name="wheel_right_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </visual>
    </link>
    <joint name="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_link"/>
        <axis xyz="1 0 0"/>
        <origin xyz="0.0 -${barrel_radius/2.0} ${wheel_radius-wheel_peakout}" rpy="0.0 0.0 0.0"/>
    </joint>

</robot>